const drivers = ['Antonia', 'Nuru', 'Amari', 'Mo'];
const returnFirstTwoDrivers = drivers   => drivers.slice(0, 2);
const returnLastTwoDrivers = drivers   => drivers.slice(-2);
const selectingDrivers = [returnFirstTwoDrivers, returnLastTwoDrivers];
const createFareMultiplier = multiplier => value => value * multiplier;
const fareDoubler = createFareMultiplier(2);
const fareTripler = createFareMultiplier(3);
const selectDifferentDrivers = (arrayOfDrivers, fn) => fn(arrayOfDrivers);
console.log(result1);
console.log(result2);
